name: Call the Tesmon workflow

on:
  push:
    branches:
      - main

jobs:
  run-tesmon-tests:
    runs-on: ubuntu-latest
    name: "Runs tesmon test on an env"
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        # with:
        #   node-version: 16.13.x
      - run: npm install -g @tesmon/cli
        shell: bash
      - run: tesmon test
        shell: bash
        env:
          TESMON_API_TOKEN: ${{ secrets.TESMON_API_TOKEN }}
          TESMON_ENVIRONMENT_ID: ${{ secrets.TESMON_ENVIRONMENT_ID }}
          TESMON_ENV: staging