name: Call the Tesmon workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: CodeMogul/test-actions/.github/workflows/tesmon.yml@main
    with:
      config-path: .github/labeler.yml
    env:
      TESMON_API_TOKEN: ${{ secrets.TESMON_API_TOKEN }}
      TESMON_TRE_ID: ${{ secrets.TESMON_TRE_ID }}