name: Run Tesmon Tests

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  tesmon_test:
    name: Tesmon Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo's default branch
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
    - name: Install CLI
      run: npm install -g @tesmon/cli
    - name: Check version
      run: tesmon -v
    # - uses: actions/labeler@v4
    #   with:
    #     repo-token: ${{ secrets.token }}
    #     configuration-path: ${{ inputs.config-path }}